# Generated by Django 4.2.16 on 2025-03-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produit',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prix',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantite',
            new_name='quantity',
        ),
    ]
